# Generated by Django 6.1.1 on 2026-09-26 08:34

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=255, verbose_name='Your name')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Your Email')),
                ('content', models.TextField(verbose_name='Comment text')),
                ('response', models.TextField(blank=True, verbose_name='Admin response')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('notify_on_reply', models.BooleanField(default=False, verbose_name='Notify on reply')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Page')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wagtail_mptt_comments.comment', verbose_name='Parent comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagtail_mptt_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author (User)')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'indexes': [models.Index(fields=['page', 'is_approved', 'date_created'], name='wagtail_mpt_page_id_8a1456_idx'), models.Index(fields=['tree_id', 'lft'], name='wagtail_mptt_comments_comm37fc')],
            },
        ),
    ]
